-- MySQL Script generated by MySQL Workbench
-- Fri Jul 17 11:21:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `motdepasse` VARCHAR(255) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produits` (
  `idproduits` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prix` VARCHAR(255) NULL,
  `quantite` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idproduits`, `user_idUser`),
  UNIQUE INDEX `idproduits_UNIQUE` (`idproduits` ASC) VISIBLE,
  INDEX `fk_produits_user_idx` (`user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_produits_user`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorie` (
  `idcategorie` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idcategorie`, `user_idUser`),
  UNIQUE INDEX `idcategorie_UNIQUE` (`idcategorie` ASC) VISIBLE,
  INDEX `fk_categorie_user1_idx` (`user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_categorie_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `idcontact` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `sujet` VARCHAR(45) NULL,
  `message` LONGTEXT NULL,
  PRIMARY KEY (`idcontact`),
  UNIQUE INDEX `idcontact_UNIQUE` (`idcontact` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Newsletter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Newsletter` (
  `idNewsletter` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`idNewsletter`),
  UNIQUE INDEX `idNewsletter_UNIQUE` (`idNewsletter` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorie_has_produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorie_has_produits` (
  `categorie_idcategorie` INT NOT NULL,
  `categorie_user_idUser` INT NOT NULL,
  `produits_idproduits` INT NOT NULL,
  `produits_user_idUser` INT NOT NULL,
  PRIMARY KEY (`categorie_idcategorie`, `categorie_user_idUser`, `produits_idproduits`, `produits_user_idUser`),
  INDEX `fk_categorie_has_produits_produits1_idx` (`produits_idproduits` ASC, `produits_user_idUser` ASC) VISIBLE,
  INDEX `fk_categorie_has_produits_categorie1_idx` (`categorie_idcategorie` ASC, `categorie_user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_categorie_has_produits_categorie1`
    FOREIGN KEY (`categorie_idcategorie` , `categorie_user_idUser`)
    REFERENCES `mydb`.`categorie` (`idcategorie` , `user_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorie_has_produits_produits1`
    FOREIGN KEY (`produits_idproduits` , `produits_user_idUser`)
    REFERENCES `mydb`.`produits` (`idproduits` , `user_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media` (
  `idmedia` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `format` VARCHAR(45) NULL,
  PRIMARY KEY (`idmedia`),
  UNIQUE INDEX `idmedia_UNIQUE` (`idmedia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`media_has_produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media_has_produits` (
  `media_idmedia` INT NOT NULL,
  `produits_idproduits` INT NOT NULL,
  `produits_user_idUser` INT NOT NULL,
  PRIMARY KEY (`media_idmedia`, `produits_idproduits`, `produits_user_idUser`),
  INDEX `fk_media_has_produits_produits1_idx` (`produits_idproduits` ASC, `produits_user_idUser` ASC) VISIBLE,
  INDEX `fk_media_has_produits_media1_idx` (`media_idmedia` ASC) VISIBLE,
  CONSTRAINT `fk_media_has_produits_media1`
    FOREIGN KEY (`media_idmedia`)
    REFERENCES `mydb`.`media` (`idmedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_has_produits_produits1`
    FOREIGN KEY (`produits_idproduits` , `produits_user_idUser`)
    REFERENCES `mydb`.`produits` (`idproduits` , `user_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `motdepasse` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  PRIMARY KEY (`idclient`),
  UNIQUE INDEX `idclient_UNIQUE` (`idclient` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
